apiVersion: v1
kind: Namespace
metadata:
  name: walrus

---

apiVersion: v1
kind: Namespace
metadata:
  name: heron

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: drone
