apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- range $key, $value := .Values.n8n.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.n8n.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.n8n.ingress.host }}
      secretName: {{ .Release.Name }}-tls-secret
  rules:
    - host: {{ .Values.n8n.ingress.host }}
      http:
        paths:
          - path: {{ .Values.n8n.ingress.paths.path }}
            pathType: {{ .Values.n8n.ingress.paths.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.n8n.service.port }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-serverless-ingress
  annotations:
      {{- range $key, $value := .Values.pysvc.ingress.annotations }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
spec:
  ingressClassName: {{ .Values.pysvc.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.pysvc.ingress.host }}
      secretName: {{ .Release.Name }}-tls-secret
  rules:
  - host: {{ .Values.pysvc.ingress.host }}
    http:
      paths:
      - path: {{ .Values.pysvc.ingress.paths.path }}
        pathType: {{ .Values.pysvc.ingress.paths.pathType }}
        backend:
          service:
            name: {{ .Release.Name }}-python-serverless
            port:
              number: {{ .Values.pysvc.service.port }}