apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data-pv
spec:
  capacity:
    storage: {{ .Values.n8n.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: {{ .Values.n8n.storage.reclaim_policy }}
  hostPath:
    path: {{ tpl .Values.n8n.storage.hostPathTemplate . }}
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-data-pv
spec:
  capacity:
    storage: {{ .Values.db.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: {{ .Values.db.storage.reclaim_policy }}
  hostPath:
    path: {{ tpl .Values.db.storage.hostPathTemplate . }}
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-serverless-data-pv
spec:
  capacity:
    storage: {{ .Values.pysvc.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.pysvc.storage.reclaim_policy }}
  hostPath:
    path: {{ tpl .Values.pysvc.storage.hostPathTemplate . }}
    type: DirectoryOrCreate