apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.n8n.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.n8n.service.port }}
      targetPort: {{ .Values.n8n.service.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: http
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-db


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | default "10Gi" }}