apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kubernetes-secrets
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-kubernetes-secrets
  template:
    metadata:
      labels:
        app: drone-kubernetes-secrets
    spec:
      serviceAccountName: drone-kubernetes-secrets
      containers:
        - name: secrets
          image: drone/kubernetes-secrets:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: drone-svc-drone-env
                  key: DRONE_SECRET_PLUGIN_TOKEN
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: drone-kubernetes-secrets
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: drone-kubernetes-secrets
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-kubernetes-secrets
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-kubernetes-secrets
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-kubernetes-secrets
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: drone-kubernetes-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: drone-kubernetes-secrets
  apiGroup: rbac.authorization.k8s.io
