apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-drone-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.drone.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.db.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}