drone:
  replicaCount: 1

  image:
    repository: drone/drone
    tag: "2"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: nginx
    host: drone.lab3.website
    annotations: {}

  env:
    DRONE_SERVER_ROOT: https://drone.lab3.website
    DRONE_GITHUB_SERVER: https://github.com
    DRONE_SERVER_HOST: drone.lab3.website
    DRONE_SERVER_PROTO: https
    DRONE_REPOSITORY_FILTER: Lab3-Spotify
    DRONE_DATABASE_DRIVER: postgres

db:
  replicaCount: 1

  image:
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

  env:
    POSTGRES_PORT: 5432

  storage: 
    size: 10Gi
    reclaim_policy: Retain
    hostPathTemplate: /run/desktop/mnt/host/d/Spotify-workspace/familiarity-playlist/dove/{{ .Release.Name }}/{{ .Release.Name }}-db