
replicaCount: 1

image:
  repository: drone/drone-runner-kube
  tag: latest
  pullPolicy: IfNotPresent

env:
  DRONE_RPC_PROTO: http
  DRONE_RPC_HOST: drone-svc
  DRONE_RUNNER_NAME: drone-runner
  DRONE_LOGS_DEBUG: true
  DRONE_RUNNER_NAMESPACE: drone


# DRONE_RUNNER_LABELS 格式要求不能用 / (repo=Lab3-Spotify/walrus 不合法)
walrus-env:
  DRONE_RUNNER_LABELS: repo:Lab3-Spotify-walrus
  DRONE_RUNNER_CAPACITY: "1"

heron-env:
  DRONE_RUNNER_LABELS: repo:Lab3-Spotify-heron
  DRONE_RUNNER_CAPACITY: "1"

dove-env:
  DRONE_RUNNER_LABELS: repo:Lab3-Spotify-dove
  DRONE_RUNNER_CAPACITY: "1"