apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webui-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.webui.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.db.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}