apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-db-pvc
spec:
  volumeName: glitchtip-db-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storage.size }}
