apiVersion: v1
kind: Secret
metadata:
  name: glitchtip-db-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: glitchtip-smtp-secret
type: Opaque
stringData:
  EMAIL_URL: {{ .Values.emailUrl | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.defaultFromEmail | quote }}
