heron:
  replicaCount: 1

  env:
    WALRUS_API_BASE_URL: "https://walrus.lab3.website"
    ENV: "staging"
    APP_TITLE: "LISLab3 Spotify Experiment"

  image:
    repository: lislab3morris/heron
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}

    host: heron.lab3.website
    paths:
      path: /
      pathType: Prefix

  # 健康檢查
  livenessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5

  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
