apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.walrus.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.walrus.image.repository }}:{{ .Values.walrus.image.tag }}"
          imagePullPolicy: {{ .Values.walrus.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.walrus.service.targetPort }}
          # entrypoint: ["/bin/sh", "-c"]
          # command: ["tail",  "-f", "/dev/null"]
          command: ["/bin/sh", "-c", "/usr/src/app/entrypoint.sh"]
          env:
            {{- range $key, $value := .Values.walrus.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
