apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.walrus.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.db.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.redis.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.rabbitmq.secretEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}