apiVersion: v2
name: glitchtip
description: GlitchTip monitoring stack
type: application
version: 0.1.0
dependencies:
  - name: glitchtip
    alias: app
    repository: https://gitlab.com/api/v4/projects/16325141/packages/helm/stable
    version: "8.2.0"
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "18.6.6"
