apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-data-pv
spec:
  capacity:
    storage: {{ .Values.db.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.db.storage.reclaim_policy }}
  hostPath:
    path: {{ tpl .Values.db.storage.hostPathTemplate . }}
  storageClassName: "" 