walrus: 
  replicaCount: 1

  image:
    repository: popopopony/walrus
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  ingress:
    enabled: true
    className: nginx
    host: lab3-walrus.ddns.net
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
  env: {}


redis: 
  replicaCount: 1

  image:
    repository: redis
    tag: 7.4.2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  storage: 
    size: 10Gi
    reclaim_policy: Retain
    hostPathTemplate: /run/desktop/mnt/host/d/Spotify-workspace/familiarity-playlist/dove/{{ .Release.Name }}/{{ .Release.Name }}-redis

  env: {}


db: 
  replicaCount: 1

  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

  storage: 
    size: 10Gi
    reclaim_policy: Retain
    hostPathTemplate: /run/desktop/mnt/host/d/Spotify-workspace/familiarity-playlist/dove/{{ .Release.Name }}/{{ .Release.Name }}-db

rabbitmq:
  replicaCount: 1

  image:
    repository: rabbitmq
    tag: 3.13-management
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5672
    targetPort: 5672
    managementPort: 15672
    managementTargetPort: 15672

  storage:
    size: 10Gi
    reclaim_policy: Retain
    hostPathTemplate: /run/desktop/mnt/host/d/Spotify-workspace/familiarity-playlist/dove/{{ .Release.Name }}/{{ .Release.Name }}-rabbitmq

  env: {}

celery:
  playlog:
    replicaCount: 1
    queue: playlog_q
    image:
      repository: popopopony/walrus
      tag: latest
      pullPolicy: IfNotPresent

  beat:
    replicaCount: 1
    image:
      repository: popopopony/walrus
      tag: latest
      pullPolicy: IfNotPresent